spring.application.name=BlackRockChallenge

# Default Profile (development)
spring.profiles.active=default

# Database Configuration (development - local PostgreSQL)
spring.datasource.url=jdbc:postgresql://dpg-d6ck4o14tr6s73c7vta0-a.oregon-postgres.render.com:5432/newchallenge
spring.datasource.username=newchallenge_user
spring.datasource.password=ePvPilDO8gx66qSzXlpFzTM8HE9EqdUS
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Jackson Configuration
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC